[env:tyee]
platform = espressif32
board = lilygo-t-sim7080g-s3
framework = arduino
monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0
build_flags =
  -I ../../config
lib_deps =
  bblanchon/ArduinoJson
  
