[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 460800
build_flags =
  -DCORE_DEBUG_LEVEL=0
  -DARDUINO_USB_CDC_ON_BOOT=1
  -I../../config
  -I../../include
  -DDEBUG_DISABLED

lib_deps =
  bblanchon/ArduinoJson @ ^7.2.0
  WiFi
  HTTPClient

src_dir = src
build_src_flags =
  -include "../../config/firmware_secrets.h"

[platformio]
src_dir = src
